#!/bin/bash

#想着有台服务器一直没有配置ssh免登陆，老是需要输入密码太麻烦就折腾了下免key登陆。网上乱七八糟的文件写的都不全对。记录下自己的步骤。备忘。

#one step 在mac客户端创建ssh密钥，算法选择rsa

ssh-keygen -t rsa

[user@www ~]$ ssh-keygen -t rsa
Generating public/private rsa key pair.
Enter file in which to save the key (/home/user/.ssh/id_rsa): y
Enter passphrase (empty for no passphrase): 
Enter same passphrase again: 
Your identification has been saved in y.
Your public key has been saved in y.pub.
The key fingerprint is:
SHA256:/bO6gCT2133qUXAKJBEMGKLXCQwoH2929292++wKLkv+0 user@www
The key's randomart image is:
+---[RSA 2048]----+
|/Ooo             |
|Xo=.             |
|+o+ +            |
|o. X .   .       |
|=.o = . S .      |
|.+oo o .   .     |
|.o.+ .. .   o    |
|+ . =    .   o   |
|...ooE.   oo.    |
+----[SHA256]-----+

将创建好的id，位置在~/.ssh/id_rsa.pub中的文件复制到目标服务器~/.ssh/authorized_keys文件中。

#step 2 配置ssh服务

PasswordAuthentication no #关闭密码登陆
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
PubkeyAuthentication yes
PermitRootLogin no #为了安全关键root登陆

#step 3:重启ssh服务

systemctl restart sshd.service

#step: ssh user@ip

done
